### PR TITLE
Prevents commits on certain branches

### PR DESCRIPTION
**Pull request by camertron**
The Android team (and potentially iOS) would like to prevent txgh from committing to certain branches (i.e. master).

@lumoslabs/platform

### CODE REVIEW

**Comment by st33b** [comment]
configure_all_the_things_banner

I like it!

**Comment by jdoconnor** [comment]
this is great. I wonder if they realize that feature branches that are branched from master will receive translations for string that aren't theirs as a byproduct of this.

**Comment by camertron** [comment]
Strings that are translated in a feature branch will get merged to master, but those strings arguably belong to master at that point anyway. The Transifex resource will also get updated, it's just that no automatic commits will be made. The Android team may well miss out on some translations, but should still be able to push them manually via the web interface.

**Comment by zvkemp** [comment]
:cool:

**Pull request merged**
